### ISSUE TITLE
ClickButton.h is missing

### ISSUE THREAD

**Issue by Cuperino** [kaixxx/Teleprompter-Footswitch#1]
Hello @kaixxx,

I attempted to compile the Arduino program and noticed ClickButton.h is not included with the program. Is there a specific Arduino library that one needs to install?

Thanks

**Comment by kaixxx** [comment]
Hello @Cuperino 
Yes, you are right. It is this llibrary: https://github.com/marcobrianza/ClickButton
I will add a reference in the readme.

Thank you!
Kai
